apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  labels:
    app: event-app
    tier: backend
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "event_management"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  APP_ENV: "production"
  APP_PORT: "8000"
  DEBUG: "false"
  LOG_LEVEL: "20"
  YOOKASSA_RETURN_URL: "http://localhost:8000/payment/callback"
  YOOKASSA_TEST: "true"
